name: UI Automation using cypress.

on:
  push:
    branches: ["master"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Cypress.io
        uses: cypress-io/github-action@be2de7b1fe1cdafb4a3c8da0a3746476ef636b65
        continue-on-error: true

      - name: print filesystem
        run: ls

      - name: print json report folder
        run: cd cucumber-json-report && ls

      - name: print filesystem
        run: ls

      - name: Generate report
        run: npm run generate:report

      - name: Upload report
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Execution Report
          path: html-report/

      - name: Upload Execution Videos
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Execution Video
          path: cypress/videos/
